onboarding = false

[keys]
prefix = "ctrl+a"

reload_config = "prefix+r"
resize_mode = "prefix+ctrl+r"

focus_pane_left = "prefix+h"
focus_pane_down = "prefix+j"
focus_pane_up = "prefix+k"
focus_pane_right = "prefix+l"

navigate_pane_left = "h"
navigate_pane_down = "j"
navigate_pane_up = "k"
navigate_pane_right = "l"

last_pane = "prefix+^"

copy_mode = "prefix+["

[[keys.command]]
key = "prefix+f"
type = "popup"
command = "~/.local/bin/herdr-sessionizer"
description = "sessionizer: fuzzy-pick a project"
width = "80%"
height = "80%"

[[keys.command]]
key = "prefix+g"
type = "popup"
command = "~/.local/bin/herdr-sessionizer ~/project/vim-help"
description = "sessionizer: vim-help"

[[keys.command]]
key = "prefix+shift+c"
type = "popup"
command = "~/.local/bin/herdr-sessionizer ~/project/go-translate-cli"
description = "sessionizer: go-translate-cli"

[[keys.command]]
key = "prefix+shift+r"
type = "popup"
command = "~/.local/bin/herdr-sessionizer ~/backend/python"
description = "sessionizer: backend/python"

[theme]
name = "tokyo-night"
auto_switch = false

[ui]
tab_bar_right = [
  { type = "datetime", format = "%m-%d-%y %H:%M" },
]
tab_bar_position = "top"
status_indicators = "symbols"

[ui.toast]
delivery = "terminal"
